a=(input("nhập chuỗi s1:"))
b=(input("nhập chuỗi s2:"))
c=(input("nhập chuỗi s3:"))
d=int(input("nhập index:"))
print("chiều dài chuỗi s1=",a)
print("chiều dài chuỗi s2=",b)
print("chiều dài chuỗi s3=",c)
print("chuỗi s4=",a[d:])
print("chuỗi s2 lặp lại 2 lần",b*2)